#!/bin/sh

if BINOC_GIT_PATH="$(which git 2>/dev/null)"; then
  _COMM_BRANCH=`git symbolic-ref --short HEAD | tr [:upper:] [:lower:]`
  _MOZILLA_BRANCH=`cd mozilla && git symbolic-ref --short HEAD | tr [:upper:] [:lower:]`
  
  if [ -n "$_MOZILLA_BRANCH" ]; then
    export BINOC_GIT_BRANCH=$_COMM_BRANCH@$_MOZILLA_BRANCH
  else
    export BINOC_GIT_BRANCH=$_COMM_BRANCH
  fi
fi

BINOC_TOOLCHAIN=`uname`
MACH_CMD=./mozilla/mach

if [ "$1" == "release" ]; then
  $MACH_CMD build
  $MACH_CMD package
  if [[ "$BINOC_TOOLCHAIN" == "MINGW32_NT-"* ]]; then
    $MACH_CMD installer
  fi
  $MACH_CMD mar
else 
  $MACH_CMD $@
fi