#filter substitution

pref("extensions.@ADDON_CHROME_NAME@.currentVersion", "0.0");
pref("extensions.@ADDON_CHROME_NAME@.enabled", true);
pref("extensions.@ADDON_CHROME_NAME@.frameobjects", true);
pref("extensions.@ADDON_CHROME_NAME@.fastcollapse", false);
pref("extensions.@ADDON_CHROME_NAME@.showinstatusbar", false);
pref("extensions.@ADDON_CHROME_NAME@.detachsidebar", false);
pref("extensions.@ADDON_CHROME_NAME@.defaulttoolbaraction", 0);
pref("extensions.@ADDON_CHROME_NAME@.defaultstatusbaraction", 0);
pref("extensions.@ADDON_CHROME_NAME@.sidebar_key", "Accel Shift V, Accel Shift U");
pref("extensions.@ADDON_CHROME_NAME@.sendReport_key", "");
pref("extensions.@ADDON_CHROME_NAME@.filters_key", "Accel Shift E, Accel Shift F, Accel Shift O");
pref("extensions.@ADDON_CHROME_NAME@.enable_key", "");
pref("extensions.@ADDON_CHROME_NAME@.flash_scrolltoitem", true);
pref("extensions.@ADDON_CHROME_NAME@.previewimages", true);
pref("extensions.@ADDON_CHROME_NAME@.data_directory", "adblockplus");
pref("extensions.@ADDON_CHROME_NAME@.patternsbackups", 5);
pref("extensions.@ADDON_CHROME_NAME@.patternsbackupinterval", 24);
pref("extensions.@ADDON_CHROME_NAME@.whitelistschemes", "about chrome file irc moz-safe-about news resource snews x-jsd addbook cid imap mailbox nntp pop data javascript moz-icon");
pref("extensions.@ADDON_CHROME_NAME@.hideimagemanager", true);
pref("extensions.@ADDON_CHROME_NAME@.subscriptions_autoupdate", true);
pref("extensions.@ADDON_CHROME_NAME@.subscriptions_listurl", "https://adblockplus.org/subscriptions2.xml");
pref("extensions.@ADDON_CHROME_NAME@.subscriptions_fallbackurl", "https://adblockplus.org/getSubscription?version=%VERSION%&url=%SUBSCRIPTION%&downloadURL=%URL%&error=%ERROR%&channelStatus=%CHANNELSTATUS%&responseStatus=%RESPONSESTATUS%");
pref("extensions.@ADDON_CHROME_NAME@.subscriptions_fallbackerrors", 5);
pref("extensions.@ADDON_CHROME_NAME@.documentation_link", "https://adblockplus.org/redirect?link=%LINK%&lang=%LANG%");
pref("extensions.@ADDON_CHROME_NAME@.savestats", true);
pref("extensions.@ADDON_CHROME_NAME@.composer_default", 2);
pref("extensions.@ADDON_CHROME_NAME@.clearStatsOnHistoryPurge", true);
pref("extensions.@ADDON_CHROME_NAME@.report_submiturl", "");
pref("extensions.@ADDON_CHROME_NAME@.recentReports", "[]");
pref("services.sync.engine.@ADDON_CHROME_NAME@", false);
